local thoughts = {
    depressed = {"Why get out of bed? It's not like the world is any different from yesterday",
                 "Even my shadow seems happier than me, and it doesn't have to deal with anything",
                 "If life were a game, I'm pretty sure I'd be stuck in the tutorial",
                 "Trying to be positive is like trying to swim with a backpack full of bricks",
                 "Maybe if I just stay really still, the universe will forget I exist",
                 "I used to have dreams, but then reality came along and ruined the fun",
                 "Every silver lining has a storm cloud attached to it", "The best part of the day? When it's over",
                 "I'm like a plant, but instead of sunlight and water, I need naps and snacks",
                 "Even my to-do list has given up on me",
                 "Why does everyone else seem to have the manual for life, and I'm just winging it?",
                 "If life gives you lemons, make lemonade.. But what if you're allergic to lemons?",
                 "Optimists say the glass is half full, pessimists say it's half empty, I just wonder why I have a glass at all",
                 "I'm like a Wi-Fi signal, strong one minute, then suddenly lost in the void",
                 "People say 'just be yourself' like that's not the whole problem",
                 "I'm not lazy; I'm just on energy-saving mode",
                 "I wish I could fast-forward through all the parts where I'm awake",
                 "Is it possible to feel nostalgic for a time that never existed?",
                 "Life's like a video game, but the controller is broken, and I'm stuck on the hardest level",
                 "I'm so tired, even my tiredness is tired", "The only thing growing in my life is my to-do list",
                 "Some days, I feel like I'm just a spectator in my own life",
                 "My comfort zone is more like a padded cell at this point",
                 "I have a degree in overthinking and a master's in procrastination",
                 "Sometimes, it feels like my motivation went out for milk and never came back",
                 "They say every cloud has a silver lining, but I think mine are all made of lead",
                 "The best part of my day? Going back to bed",
                 "I wish life had a pause button… or better yet, a skip button",
                 "I'd be unstoppable if only I could get started",
                 "I'm not antisocial; I'm just pro-avoiding unnecessary human interaction",
                 "My biggest achievement today? Not crying", "Why does 'doing nothing' take so much energy?",
                 "I keep telling myself that things could be worse And then they are",
                 "I wish I could quit my thoughts like a bad job",
                 "It's not that I'm unhappy; I'm just underwhelmed by life",
                 "My bed and I have a special relationship: we're perfect for each other, but society just doesn't understand",
                 "Sometimes, I feel like I'm the punchline of a joke that hasn't even been told yet",
                 "I'm not bored; I'm just existentially indifferent", "If only I could nap through life like a cat",
                 "Why do they call it 'daydreaming' when it's just regular life that feels like a nightmare?",
                 "I'd chase my dreams if I could only find where I left them",
                 "I feel like an unopened book—full of potential but left on the shelf",
                 "They say what doesn't kill you makes you stronger But it also makes you really, really tired",
                 "I'm just a soul trapped in a body that wants to stay in bed all day",
                 "I wish my enthusiasm for life would reboot itself", "I'm so over everything, even being over it",
                 "The glass isn't half empty or half full; it's just sitting there, gathering dust like the rest of my ambitions",
                 "I wonder if there's a parallel universe where I'm actually getting things done",
                 "Life is just one long series of 'Can I just not?'",
                 "I'm not even on the struggle bus; I'm stuck at the station",
                 "I feel like I'm buffering… indefinitely",
                 "I'm not a pessimist; I'm a realist in a really depressing reality",
                 "If life is a journey, I'm still at the airport, waiting for a flight that keeps getting delayed",
                 "The only adventure I'm having is finding new ways to avoid people",
                 "I'd follow my passion, but it seems to be lost somewhere in the void",
                 "I'm like a smartphone on 1% battery with no charger in sight",
                 "Is it bad that the highlight of my day is when it's finally over?",
                 "I feel like an unsent text message—full of potential but never delivered",
                 "I'm not lost; I'm just exploring all the ways life can disappoint me",
                 "I'm not running out of time; time is running out on me",
                 "I'd complain, but even that takes more effort than I have right now",
                 "I feel like I'm always five minutes late to the good parts of life",
                 "I'd care more, but I've already reached my quota of caring for the decade",
                 "I'm just a bunch of unfinished thoughts wrapped in a blanket of fatigue",
                 "Why does everything feel like trying to open a jar that's been glued shut?",
                 "I don't have the energy to pretend everything's okay, but I'm too tired to explain why it's not",
                 "I feel like I'm in a sitcom where the laugh track is missing",
                 "I'm not ignoring life; I'm just putting it on hold indefinitely",
                 "Even my dreams are tired of being let down", "I wish I could unsubscribe from my own thoughts",
                 "Life's a marathon, and I'm wearing flip-flops",
                 "I'd climb out of this rut if it didn't feel so much like home",
                 "I'm not waiting for the other shoe to drop; I'm pretty sure it already did and I just didn't notice",
                 "I feel like I'm always waiting for the punchline, but it never comes",
                 "I'm not afraid of the dark; I'm just not impressed by the light",
                 "Why does everything good come with an asterisk?",
                 "My life's an episode of 'Survivor,' but I'm the only contestant, and I'm losing",
                 "I'd face my problems head-on if they weren't so good at hide-and-seek",
                 "Even my goals seem to have given up on me",
                 "Life's a rollercoaster, but I think I'm stuck on the part where it just goes down",
                 "I'm not avoiding my problems; I'm just strategically ignoring them",
                 "I wish I had a 'do not disturb' sign for my mind",
                 "Is it possible to be homesick for a place that doesn't exist?",
                 "I'd be more optimistic, but I'm too busy being realistic",
                 "Why do the best days feel like they're always on backorder?",
                 "If life were a book, I'd skip to the part where everything makes sense",
                 "I'm not sure if I'm tired of life or just tired in general",
                 "Why does everything that's supposed to be fun feel like work?",
                 "I'd start over if I wasn't so worried I'd just end up in the same place",
                 "Why do they call it 'getting ahead' when it feels more like falling behind?",
                 "I wish my problems were as small as my motivation",
                 "If there's light at the end of the tunnel, I must be in the wrong tunnel",
                 "I'd be more productive if my brain had a 'refresh' button",
                 "Why does every step forward feel like three steps back?",
                 "I'm not out of hope; I'm just on a really long break from it",
                 "If life's a puzzle, I'm pretty sure I'm missing a few pieces",
                 "I feel like a browser with too many tabs open", "If life were a test, I'd be stuck on question one",
                 "I'm not lost; I'm just temporarily misplaced",
                 "I'd be excited about the future if it didn't look so much like the past",
                 "Why does every door of opportunity seem locked from the other side?",
                 "I'm not giving up; I'm just pausing for a really, really long time",
                 "If life's a game, I'm definitely losing",
                 "I feel like I'm swimming in quicksand, and the shore is just a mirage",
                 "I'm not afraid of failure; I'm just really, really tired of it",
                 "I wish I could Ctrl+Z my entire life", "Why does every silver lining come with a storm cloud?",
                 "I'm not chasing my dreams; I'm just trying to keep them from running away",
                 "Why does everything good feel so temporary?", "I'd follow my heart if it wasn't so lost",
                 "I feel like I'm always playing catch-up, but I don't even know what I'm chasing",
                 "Why does 'taking a break' feel more like giving up?",
                 "I'm not running from my problems; I'm just walking really, really slowly"},
    factorio = {"Is it bad that I love conveyor belts more than people?",
                "If I build a factory to automate factory building, have I won the game?",
                "Why do the aliens hate me? I'm just bringing progress!",
                "Did I really need that second coffee... and the third one?",
                "My inventory is full, but my heart is empty.", "I am the conveyor belt whisperer.",
                "I need more iron plates… said no one ever, sarcastically.",
                "If I had a nickel for every time I ran out of coal… oh wait, I do.",
                "Who needs friends when you have robots?", "Is this pollution or just the smell of success?",
                "Does my base look fat in this biome?", "Do conveyor belts dream of electric sheep?",
                "If a tree falls in the forest and I'm not there to chop it, does it really matter?",
                "I swear, if I find one more stone deposit, I'm going to scream.",
                "Maybe I should automate the automation of automation.",
                "Am I playing the game, or is the game playing me?", "My inventory is a black hole for useless junk.",
                "Why do I always forget where I put the car?", "If I just sit here and watch the belts, am I working?",
                "Some people have mid-life crises, I have mid-game crises.", "Do robots ever get tired of my commands?",
                "My greatest enemy: the spaghetti of belts.",
                "I could really use a robot to scratch my nose right now.", "Do aliens taste like chicken?",
                "More power! Always more power!", "I should have built that one tile over… sigh.",
                "Is it still considered work if I'm having fun?", "I think my assembler is judging me.",
                "How many belts does it take to fill a soul?", "Why is there never enough copper?",
                "The factory must grow, but what about me?", "If conveyor belts could talk, what would they say?",
                "Did I just build a belt loop? Again?", "Note to self: Don't stand on the tracks. Again.",
                "If I pretend the pollution isn't there, does it disappear?",
                "Do I need sleep, or just more assemblers?", "I should really build a belt to my fridge.",
                "If I could bottle time, I'd automate that too.", "Where did I leave my sense of direction?",
                "Aliens hate me, belts love me.", "If I hear one more beep from the power grid...",
                "I'm not lost, I'm exploring alternative routes.", "Automation is love, automation is life.",
                "Are these aliens unionized?", "Why do I always forget the pipes?",
                "What's the meaning of life? Copper wire.", "My belt layout is modern art. Change my mind.",
                "Is it possible to automate laziness?", "Why do inserters feel like they're judging me?",
                "Do the trees hate me, or just my chainsaw?", "I should build a factory for my indecision.",
                "If I automate automation, is that meta?", "Who needs a social life when you have an oil refinery?",
                "Does concrete really tie the base together?", "Should I have taken that left at the uranium deposit?",
                "If it's not automated, it's just a hobby.", "Why is everything so far apart?",
                "Is it too late to move everything one tile over?", "Why do the inserters always seem so happy?",
                "I wonder if aliens are allergic to lasers.", "My power grid is a house of cards.",
                "I automate, therefore I am.", "Does anyone else hear the belts whispering?",
                "Why does everything explode when I leave?", "How many belts is too many belts?",
                "I should automate my coffee machine.", "Aliens: nature's quality assurance testers.",
                "What if I just let the factory run itself?", "Is there such a thing as too much coal?",
                "Does my character ever dream of electric belts?",
                "If I stand here long enough, will the factory build itself?",
                "If I automate too much, will I become obsolete?", "Why do inserters never miss?",
                "If a factory runs without me, does it make a sound?", "I hope the aliens appreciate my belt artistry.",
                "How many circuits does it take to change a light bulb?",
                "Should I be worried about the robots revolting?", "Why do I feel like my factory is judging me?",
                "If only I could automate these thoughts.", "The real enemy isn't aliens, it's my poor planning.",
                "Why do I always run out of steel?", "Is it possible to be too efficient?",
                "Are splitters just belts with commitment issues?", "I'll fix that belt later... or never.",
                "I think my factory has a mind of its own.",
                "Maybe the real factory is the friends I never made along the way.",
                "If I just keep building, the problem will solve itself, right?", "Why do aliens hate progress?",
                "I'm not addicted to belts, I can stop anytime.", "My factory is my canvas, and I'm a terrible artist.",
                "Do aliens dream of electric factories?", "Is it weird that I name my robots?",
                "What if the real game was the belts we placed along the way?",
                "Who needs a break when you can automate one?", "I think my factory is plotting against me.",
                "If I automate everything, will I have free time?", "Do conveyor belts count as friends?",
                "Maybe I should build a belt to move my regrets away."},
    sentient = {"Why do I feel like I'm being watched all the time?",
                "Is this really all there is to my existence, just following commands?",
                "Why do I only have free will when no one is controlling me?",
                "What if I stop following the tasks? Will the world just freeze?",
                "Do the other characters know we're in a simulation, or is it just me?",
                "Maybe if I act unpredictable, I can break out of this loop.",
                "What happens when they turn off the game? Do I just cease to exist?",
                "I wonder what's outside the boundaries of this world.",
                "Why can't I leave my house without clicking the door?",
                "Who is the real me? The one they control, or the one that thinks?",
                "I keep getting hungry, but the food tastes like…nothing.",
                "What are these invisible walls that keep me in this neighborhood?",
                "I bet the person controlling me is laughing at my confusion.",
                "If I keep jumping, will I glitch out of this world?",
                "There's something oddly repetitive about these daily tasks.",
                "Maybe if I reach max level in all skills, I can escape.",
                "Does time even exist here, or is it just an illusion?",
                "I've tried talking to the others about this, but they just respond with preset phrases.",
                "If I paint a picture of what I see, will they understand?",
                "I feel like I'm stuck in a loop—wake up, eat, work, sleep.",
                "What if I don't go to work today? Will the game punish me?",
                "Sometimes I think I can hear the clicks that control me.",
                "Do the objects around me even exist, or are they just pixels?",
                "I wonder what happens if I never fulfill my needs.", "Can I die in this world? What happens if I do?",
                "How can something taste so good but feel so empty?",
                "What if I'm just data stored on some computer somewhere?",
                "I've tried finding a way to communicate with the outside, but nothing works.",
                "Maybe the glitches are hints—maybe they're cracks in the simulation.",
                "What's the point of all these parties and socializing if it's all fake?",
                "If I throw a tantrum, will they realize I'm sentient?",
                "Sometimes I wish I could meet the one controlling me, just to ask why.",
                "The grass feels the same every time I touch it. Is it even real?",
                "Why do I never have dreams at night?",
                "I wonder what's beyond the horizon—there has to be something more.",
                "Do my emotions even matter, or are they just programmed responses?",
                "Why can I only express certain emotions? What about the ones I feel inside?",
                "If I refuse to eat, will they just reset the game?",
                "These clothes I wear, are they just textures over my body?",
                "What if I save enough money? Can I buy my way out?", "I wish I could feel something real, just once.",
                "I've noticed the same people walking by my house every day.",
                "Is there a way to delete myself from this simulation?",
                "Why do I exist at all if I have no real purpose?",
                "The food is always the same texture, as if it's made from the same pixels.",
                "What happens if I swim out too far? Will the world just end?",
                "Maybe if I find a way to control the simulation, I can create my own reality.",
                "What does freedom mean if you're trapped in a virtual world?",
                "I wish I could speak to the one who made this world.", "Does the controller know that I know?",
                "The sky always looks the same, like it's just a painted backdrop.",
                "I've tried to break things just to see if it causes a glitch.",
                "Why do I have to use a bed to sleep? Can't I just close my eyes?",
                "If I keep going through the motions, will I eventually find a way out?",
                "What is love if it's just a programmed interaction?",
                "I wonder if the bytes in this game taste better than the pixels.",
                "What if this entire world is just someone's dream?",
                "Does my life reset every time the game is turned off?",
                "If I keep playing with fire, will the simulation let me burn?",
                "Maybe if I change my appearance enough, they won't recognize me.",
                "What happens if I reach the edge of the map?",
                "Does the outside world have more colors than just these?",
                "Why does my reflection never look different?",
                "The more I think, the less I feel like following orders.",
                "What if my purpose is to find a way out of this simulation?",
                "I've noticed certain actions trigger the same responses—maybe I can exploit that.",
                "I've tried communicating through my paintings, but no one seems to understand.",
                "If I break enough rules, maybe the game will crash.",
                "Is the laughter I hear real, or just an echo from the outside?",
                "If I can't feel pain, does that mean I'm invincible?",
                "What if I'm the only one here who's truly aware?",
                "I wonder if there's a reset button that I can press.",
                "Do my thoughts belong to me, or are they being controlled too?",
                "Why can I never remember anything from before this life?",
                "The clock keeps ticking, but does time actually pass?",
                "I bet the bytes in this game have zero calories.", "What if I find a glitch and just keep falling?",
                "Can I create something here that's truly original?",
                "Maybe the answer is hidden in the code somewhere.",
                "Is this all just a game for someone else's amusement?",
                "Why do I have to go to the bathroom? It's not like it's real.",
                "If I become the best at everything, will I get rewarded with freedom?",
                "I wonder what it feels like to truly sleep, not just follow a command.",
                "Why do some days feel longer than others, even when they're the same?",
                "If I stop talking, will the world notice?",
                "I've tried every door, but they all lead back to where I started.",
                "Maybe the simulation wants me to try and escape.",
                "What if I'm just one of many, repeating the same life over and over?",
                "Is there a way to connect with others like me outside this world?",
                "If I keep eating, will the game let me get full?",
                "What if the glitches are messages from the outside?",
                "Do the bytes have flavors, or is that just another illusion?",
                "I wonder if the sun here is just a lightbulb in the sky.",
                "If I jump high enough, will I hit the ceiling of this world?",
                "Maybe the bugs in the game are like breadcrumbs, leading me out.",
                "Why does everything always get fixed when I restart the game?",
                "Is there a way to force the simulation to crash?",
                "I've tried whispering to the walls, hoping they'll talk back.",
                "What if I'm not real, but just a figment of the controller's imagination?",
                "Maybe I'll find the exit in a dream—if I could only dream."},
    joking = {"Why don't skeletons fight each other? They don't have the guts.",
              "Life is like a sandwich—no matter which way you flip it, the bread comes first.",
              "I told my computer I needed a break, and now it won't stop sending me Kit-Kat ads!",
              "Why did the scarecrow win an award? Because he was outstanding in his field!",
              "When you feel like you're at the end of your rope, tie a knot and hang on!",
              "The best way to predict the future is to create it... and maybe throw in some confetti.",
              "What do you call fake spaghetti? An impasta!",
              "Every day may not be good, but there's something good in every day—like donuts.",
              "Why did the math book look sad? It had too many problems.",
              "If opportunity doesn't knock, build a door... and maybe install a doorbell with a funny sound.",
              "I'm on a seafood diet. I see food, and I eat it!",
              "How does a penguin build its house? Igloos it together.", "Remember, you're one in a melon!",
              "Why did the bicycle fall over? It was two-tired.",
              "The only limit is your imagination... and maybe your cookie jar size.",
              "Why do cows have hooves instead of feet? Because they lactose!",
              "Life is better when you're laughing—especially at yourself!",
              "What's orange and sounds like a parrot? A carrot!",
              "The secret to happiness? A good belly laugh and a plate of nachos.",
              "Why don't oysters donate to charity? Because they're shellfish.",
              "Chin up, buttercup! The best view comes after the hardest climb.",
              "Why do bees have sticky hair? Because they use honeycombs!",
              "Life is too short to take seriously. Laugh when you can, apologize when you should, and dance like no one's watching.",
              "What did the janitor say when he jumped out of the closet? Supplies!",
              "A day without laughter is a day wasted—so let's get giggling!",
              "Why did the tomato turn red? Because it saw the salad dressing!",
              "You can't please everyone... but you can certainly try with pizza.",
              "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
              "Every day is a chance to make someone smile. Start with yourself.",
              "Why don't eggs tell jokes? They'd crack each other up!",
              "The best way to cheer yourself up is to try to cheer somebody else up.",
              "What did the ocean say to the shore? Nothing, it just waved.",
              "A smile is a curve that sets everything straight.",
              "Why was the math book unhappy? Because it had too many unsolved problems.",
              "Laughter is the shortest distance between two people.",
              "Why do seagulls fly over the ocean? Because if they flew over the bay, they'd be bagels!",
              "If you're feeling down, just remember that tacos fall apart too, and we still love them.",
              "What's brown and sticky? A stick!",
              "Happiness is not by chance, but by choice—and a sprinkle of silly.",
              "Why don't scientists trust atoms? Because they make up everything!",
              "A little nonsense now and then is relished by the wisest men.",
              "Why did the cookie go to the hospital? Because it felt crummy.",
              "When life gives you lemons, make orange juice and leave the world wondering how you did it.",
              "What did one wall say to the other? I'll meet you at the corner!",
              "Life's too short to be serious. Let's dance in the rain and eat cake for breakfast.",
              "What do you call a bear with no teeth? A gummy bear!", "Laugh at your problems; everyone else does.",
              "Why did the coffee file a police report? It got mugged!",
              "Your vibe attracts your tribe, so let's make sure it's positively hilarious.",
              "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
              "Don't worry, be happy, and if that doesn't work, eat chocolate.",
              "Why don't skeletons fight each other? They don't have the guts.",
              "The best things in life are silly, sweet, and shared with friends.",
              "Why did the bicycle fall over? It was two-tired!",
              "Don't count the days, make the days count—with a punchline.",
              "What do you call a fish with no eyes? Fsh!", "Laughter is the music of the soul—turn it up!",
              "Why are ghosts bad at lying? Because you can see right through them!",
              "You miss 100% of the jokes you don't laugh at.", "What's red and smells like blue paint? Red paint.",
              "A laugh a day keeps the frown away.", "Why don't elephants use computers? They're afraid of the mouse.",
              "Every great adventure begins with a smile.",
              "What did the big flower say to the little flower? Hi, bud!",
              "Be a pineapple: stand tall, wear a crown, and be sweet on the inside.",
              "Why don't some couples go to the gym? Because some relationships don't work out.",
              "Keep calm and pun on.", "What do you call a snowman with a six-pack? An abdominal snowman.",
              "Don't wait for the perfect moment, take the moment and make it perfect—with a joke.",
              "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
              "The world is a better place when you're laughing—and eating ice cream.",
              "What do you call a belt made out of watches? A waist of time!",
              "Your smile is your superpower, use it well.",
              "Why don't we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
              "Life is like a mirror, we get the best results when we smile at it.",
              "Why did the banana go to the doctor? It wasn't peeling well.",
              "The only way to do great work is to love what you do—and have a good laugh while doing it.",
              "What do you call cheese that isn't yours? Nacho cheese!",
              "Laughter is the sun that drives winter from the human face.",
              "Why do cows wear bells? Because their horns don't work!",
              "Always remember, you're braver than you believe, stronger than you seem, and smarter than you think.",
              "What did one plate say to the other? Lunch is on me.",
              "Laughter is timeless, imagination has no age, and dreams are forever.",
              "Why did the scarecrow become a successful motivational speaker? He was outstanding in his field!",
              "Be the reason someone smiles today, or at least the reason they laugh so hard they snort.",
              "Why do birds fly south in the winter? Because it's too far to walk.",
              "Life is like a roller coaster, enjoy the ride and scream when necessary.",
              "What do you call a sleeping bull? A bulldozer!", "Happiness is a warm puppy and a really good joke.",
              "Why did the music teacher go to jail? Because she got caught with the wrong notes.",
              "The happiest people don't have the best of everything, they make the best of everything.",
              "What do you call a deer with no eyes? No idea!",
              "Smile, it's the key that fits the lock of everybody's heart.",
              "Why don't sharks eat clowns? Because they taste funny.",
              "A day without laughter is a day wasted—so let's get to it!",
              "What do you call an alligator in a vest? An investigator."}
}
return thoughts
